### ISSUE TITLE
Forced toolchain path

### ISSUE THREAD

**Issue by joh06937** [mensi/teensy_bare_metal#1]
In the Makefile under .../common/, COMPILERPATH is hard-coded to point to /usr/bin. This works fine for most cases, but if trying to build using a toolchain installed elsewhere (such as myself, using Cygwin), it doesn't work. It'd be nice to at least check to see if the cross compiler is in the path prior to doing this.

Obviously, nobody likes to get a, "Fix this k thankx," so I'd be more than happy to do the work myself and submit a pull request. Would that be okay with you all?

(Just as an aside, I'm an embedded software engineer by trade who just got a Teensy 3.6 and who's looking to forgo the Arduino stuff because it's more fun for him this way.)

**Comment by mensi** [comment]
I guess this is somewhat of a philosophical question: How powerful should the Makefile be by default so you don't have to change it, while still being simple enough to easily understand.

However, the compiler path seems a bit overly crude. Can you have a go with 10c34bd to see whether that works on Cygwin?
